version: '3'

services:
  integration-exact-online:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    image: myparcelcom/integration-exact-online:v1-dev
    working_dir: /opt/app
    environment:
      - LOG_LEVEL=$LOG_LEVEL
    ports:
      - $APP_PORT:80
    volumes:
      - .:/opt/app
      - composercache:/.composer/cache
    networks:
      - default
      - micronet

  redis:
    image: redis:3.2
    volumes:
      - redisdata:/data
    networks:
      - default

volumes:
  redisdata:
    driver: local
  composercache:
    driver: local
  postgresdata:
    driver: local

networks:
  default:
    driver: bridge
  micronet:
    external: true
