version: '3'

services:
  integration-exact:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      args:
        REGISTRY: ${REGISTRY}
    image: myparcelcom/integration-exact:v1-dev
    working_dir: /opt/app
    environment:
      - LOG_LEVEL=$LOG_LEVEL
    ports:
      - $APP_PORT:80
    volumes:
      - .:/opt/app
      - composercache:/.composer/cache
    networks:
      - default
      - micronet

  redis:
    image: redis:3.2
    volumes:
      - redisdata:/data
    networks:
      - default

  postgres:
    image: postgres:11.5
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
    ports:
      - $DB_PORT_FORWARD:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - default

volumes:
  redisdata:
    driver: local
  composercache:
    driver: local
  postgresdata:
    driver: local

networks:
  default:
    driver: bridge
  micronet:
    external: true
